### ISSUE TITLE
ksi-tip tag neignoruje newline

### ISSUE THREAD

**Issue by ItsMACO** [fi-ksi/web-frontend-angular#40]
`<ksi-tip>`, ktorý má nasledujúci riadok prázdny má prázdny content:
```
<ksi-tip title="Tento ksi-tip má prázdny content">

Tento text sa bude nachádzať až pod ksi-tip elementom.

</ksi-tip>
```
Napr. úloha [Vzdálená práce na Linuxovém počítači](https://naskoc.fi.muni.cz/ulohy/33)
PR: https://github.com/fi-naskoc/seminar/pull/22/files#diff-cecadc346476f7a82070c51b934094d2444e04353a069fb87a90c5ba726eee0eR47-R58

Ak odstránime newline za opening tagom, dostaneme správny result
```
<ksi-tip title="Tento ksi-tip bude fungovať">
Tento text sa správne ukáže v contente.
</ksi-tip>
```
Napr. úloha [PRŮBĚH SEMESTRU](https://naskoc.fi.muni.cz/ulohy/23)
PR: https://github.com/fi-naskoc/seminar/pull/27/files#diff-1728a4c32eccf04fadc2f9611e81c0efead89bf9f163901cbd149a1e04296091R51-R53

**Comment by esoadamo** [comment]
Přemýšlím, jestli to není spíš chyba backendu. BE totiž posílá na FE:
```html
<p>
    <ksi-tip title="[title]">
</p>
<p>
    [content]
</p>
<p>
    </ksi-tip>
</p>
```
přičemž správně by to mělo být
```html
<p>
    <ksi-tip title="[title]">
        [content]
    </ksi-tip>
</p>
```

BE tedy neposílá validní HTML elementy, které FE vyhledává. Otázka tedy je, jestli upravit parsování na FE (aby fulltextově hledal `</ksi-tip>`)  nebo na BE (aby posílal validní HTML).

**Comment by BorysekOndrej** [comment]
Jen dodám, že prázdné řádky v Md občas jsou potřeba, například když chcete začít seznam. Např. dolor v následujícím příkladu Github vidí jako seznam, ale pandoc vyžaduje prázdný řádek mezi lorem a ipsum.

```
lorem
- dolor
```

Aktuálně libovolný prázdný řádek ukončí ksi-tip.

**Comment by ItsMACO** [comment]
@esoadamo Navrhujem to fixnúť na BE, keďže ten response z BE nie je valídny. Neviem či sa na to stíham teraz najbližšie pozrieť, prinajhoršom to môžeme nechať na Hackathon. Našťastie momentálny workaround, že sa odstránia prázdne riadky funguje, takže to veľmi nehorí.

**Comment by esoadamo** [comment]
Souhlas. Já na to zkusím mrknout dneska :slightly_smiling_face:
