### ISSUE TITLE
Vylepšení zobrazování výsledků úlohy

### ISSUE THREAD

**Issue by danyroza** [fi-ksi/web-frontend-angular#50]
1. Bylo by dobré mít točícího se Karlíka, než se načtou všechny výsledky
2. Výsledky se 100 záznamy by mohli ukazovat 100+, aby řešitelé věděli, že jich není pouze 100 (což je limit backendu)

**Comment by esoadamo** [comment]
Resolved by https://github.com/fi-ksi/web-frontend-angular/commit/21a7e0d67211dad3bddee48b8e89759b496eba75
