### ISSUE TITLE
GitHub username je povinný aj pre riešiteľov

### ISSUE THREAD

**Issue by ItsMACO** [fi-ksi/web-frontend-angular#56]
Keď si chcem robiť zmeny v profile ako riešiteľ, som povinný zadať svoj GitHub username, pretože je to povinné pole nielen pre organizátorov.
Bez zadania username nemôžem vykonať zmeny v profile, tlačítko "Uložit změny" je disabled.

Toto prišlo aj ako spätná väzba od riešiteľa na ksi@fi:

**[KSI-WEB] Zpetna vazba**
_2. septembra 2022 - 18:03_
> Jako první bych chtěl vytknout to, že v nastavení nelze změnit jakékoliv nastavení, tudíž jméno, přijmení, velikost trička apod. Přidat schopnost měnit tyto možnosti by určitě ušetřilo několik emailů o změně účtu, a také uživatelům ušetřilo nervy nad klikáním tlačítka "Uložit změny", které na kliknutí nijak nereaguje.

Zreprodukované vo verzii `220904.143147`

**Comment by esoadamo** [comment]
Díky za report, v https://github.com/fi-ksi/web-frontend-angular/commit/df652bbc23df788bfcba2909317e2b6e005e43b4 upraveno tak, aby web nevyžadoval GH username
