### ISSUE TITLE
Nesprávny časový údaj na diskusii

### ISSUE THREAD

**Issue by DianaValkova** [fi-ksi/web-frontend-angular#59]
Po pridaní príspevku do diskusií sa zobrazuje časový údaj posunutý 2 hodiny dozadu.

**Comment by esoadamo** [comment]
Problém je trochu složitější, backend totiž posílá všechny časy v GTM (např. BE pošle `2022-10-04T19:41:29`, což by se správně mělo přeložit jako 2022-10-04 21:41:29 SEZČ), takže FE si už asi myslí, že datum je v lokální časové zóně uživatele.
Angular [by-default](https://angular.io/api/common/DATE_PIPE_DEFAULT_TIMEZONE) převádí všechny časy do lokální časové zóny.
Možná tedy bude nejlepší donutit BE, aby posílal i údaje o časové zóně?
