### ISSUE TITLE
Duplicitní vyhodnocení úloh

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-frontend-angular#76]
@GiraffeReversed při práci na vylepšení [nástěnky](https://github.com/fi-ksi/dashboard) zjistila, že pro všechny moduly z poslední doby máme v DB sudý počet odevzdání.
V DB jsem to zkontroloval a vypadá to tak. Zkusil jsem v prohlížeči odevzdat úlohu a všiml jsem si, že service worker dělá dva (identické?) dotazy na backend.
To by možná vysvětlilo, proč jsme měli problém s konkurentními odevzdáními (https://github.com/fi-ksi/web-backend/issues/157, https://github.com/fi-ksi/web-backend/issues/155).

Jedno zmáčknutí tlačítka odevzdat má následující efekt:
![image](https://user-images.githubusercontent.com/6960421/197398950-be3b27a9-588b-4939-b7ce-c83ae68a2ffd.png)

**Comment by esoadamo** [comment]
Díky za zjistění! Toho jsem si vůbec nešiml -- podle včeho na výsledek submitu od nějakého bodu ve vývoji poslouchaly dvě různé fce, tak se zavolal dvakrát. Vynutil jsem teď pouze jedno spuštění, na produ se to objeví po aktualizaci cachce.

Fix: https://github.com/fi-ksi/web-frontend-angular/commit/304084dc1674b202565ad7c370480785bc91a692
