### ISSUE TITLE
Nečitatelný text dark mode

### ISSUE THREAD

**Issue by danyroza** [fi-ksi/web-frontend-angular#81]
> Dobrý deň prajem. Na úlohe /510 s použitým darkmodom je text v úlohe takmer nečitateľný. (text sa zmení iba na šedý a je zle čitateľný na bielom pozadí)

**Comment by esoadamo** [comment]
Jedná se o sortable module, je zapotřební [fixní barvy přepsat na proměnné](https://github.com/fi-ksi/web-frontend-angular/blob/main/src/app/components/tasks/task-module/task-module-sortable/task-module-sortable-item/task-module-sortable-item.component.scss)

**Comment by esoadamo** [comment]
> nelze moc poznat, kde se při zadávání kódu do řešení nacházím, protože kurzor splývá s pozadím. A například i na konci lekce o Řetězcích - print(f"Jsem tady již od verze {verze}!") - je {verze} také v černé barvě a při noční study session mi chvíli trvalo zanalyzovat, proč tam je vynechaný prostor.
