### ISSUE TITLE
Vždy rozbalený rozbalovací blok sa zobrazuje ako zabalený

### ISSUE THREAD

**Issue by KaPr3** [fi-ksi/web-frontend-angular#83]
Rozbalený rozbalovací blok, ktorý je popísaný na wiki ako

```<div class="panel panel-ksi panel-group">
<div class="panel-heading panel-heading-ksi">
<h4 class="panel-title">Nadpis</h4>
</div>
<div class="panel-body">
Text
</div> </div>
```

sa zobrazuje zabalený a chýba mu nadpis.
Reprodukcia: https://ksi.fi.muni.cz/ulohy/546

**Comment by esoadamo** [comment]
Fixed by 506787a845d519a1ac4dbb6776d121b77e954d2a
