### ISSUE TITLE
<ksi-pseudocode> neformátuje text ako pseudokód

### ISSUE THREAD

**Issue by Bianka89456** [fi-ksi/web-frontend-angular#89]
Skopírovala som úlohu Vaření proměnných z minulého roku do nového ročníka, avšak <ksi-pseudocode> neformátuje text ako pseudokód, resp. ho neformátuje vôbec. Hoci je to napísané rovnako ako minulého roku, a minulého roku formátovanie fungovalo.

**Comment by esoadamo** [comment]
Fixed by https://github.com/fi-ksi/web-backend/pull/199
