### ISSUE TITLE
Web nezobrazuje správně EduLint feedback

### ISSUE THREAD

**Issue by GiraffeReversed** [fi-ksi/web-frontend-angular#93]
### Současné chování

Při odevzdání následujícího kódu v úloze [Seznámení s Pythonem](https://ksi.fi.muni.cz/ulohy/593) web vypíše "Skvělá práce! EduLint nenašel v tvém kódu žádná další zlepšení."

```py
n = int(input())

for i in range(n):
    pass
else:
    print("error")
    
print(42)  # namísto tohoto řádku vepište vlastní správné řešení
```

### Očekávané chování

Web vypíše informaci, že kód obsahuje jeden problém: forbidden for loop with else. Podle výpisu z devtools EduLint API vrátí seznam, který tento problém obsahuje.

**Comment by esoadamo** [comment]
Resolved by https://github.com/fi-ksi/web-frontend-angular/commit/203f394a3db0ef02aacac781261bfec9a17075e0
