### ISSUE TITLE
Presmerovanie prihláseného užívateľa z admina

### ISSUE THREAD

**Issue by michalstanik1** [fi-ksi/web-frontend-angular#95]
Keď mám otvorené https://ksi.fi.muni.cz/admin/ulohy, tak po nejakej dobe, zavretí a otvorení prehliadača sa tá stránka zmení na https://ksi.fi.muni.cz/ (neviem si nechať otvorené admin rozhranie dlhšiu dobu/cez reštart počítača).

Neprihlásený používateľ je korektne presmerovaný preč z admina, ale pravdepodobne aj pri prihlásenom používateľovi s admin právami sa stáva, že ho to presmeruje skôr, ako ho to prihlási / ako sa overí jeho prihlásenie.

Řešení bude nejspíš přidat timeout třeba 3 sekundy než tě to jako odhlášeného přesměruje pryč z admina

**Comment by esoadamo** [comment]
Solved by https://github.com/fi-ksi/web-frontend-angular/commit/841e565826e3d4a92df9a63f3ad5ea0a185afb05
