### ISSUE TITLE
Update EduLintu

### ISSUE THREAD

**Issue by GiraffeReversed** [fi-ksi/web-frontend-angular#97]
1. zobrazovat texty všech nahlášených problémů, nejen jejich počet (stačí jako obyčejný text s doplněním, že pro víc informací pořád můžou na web EduLintu).
2. přidat požadavku `source_id` podle [dokumentace API](https://edulint.com/api/). `ksi:taskId_<id>:moduleId_<id>:userId_<id>` je lepší, než `ksi:taskId_<id>:moduleId_<id>` je lepší než `ksi`. UserId mi stačí hash, u modulů a tasků bych byla ráda za skutečná id, ať je případně můžu spárovat se zadáním.

**Comment by esoadamo** [comment]
Solved by https://github.com/fi-ksi/web-frontend-angular/commit/d1a3bab7fb11d0b51ae3b4d6740abf306119b9fd and https://github.com/fi-ksi/web-backend/commit/3ee4a82cd9b40967c36cae331e892f224a19b4f9
